module.exports = {
    armor: [
        {
            name: 'Buff Coat',
            size: 'S',
            dr: '2',
            def: 0,
            init: 0,
            rec: 2,
            fatigue: -1,
            skill: 0,
        },
        {
            name: 'Gambeson',
            size: 'S',
            dr: '3',
            def: 0,
            init: 0,
            rec: 0,
            fatigue: -1,
            skill: -2
        },
        {
            name: 'Leather',
            size: 'S',
            dr: '4',
            def: -1,
            init: 1,
            rec: 1,
            fatigue: -1,
            skill: -2
        },
        {
            name: 'Coat of Plates',
            size: 'M',
            dr: '2/d',
            def: -4,
            init: 0,
            rec: 5,
            fatigue: -2,
            skill: -2
        },
        {
            name: 'Lamellar',
            size: 'M',
            dr: '3/d',
            def: -4,
            init: 5,
            rec: 0,
            fatigue: -3,
            skill: -4
        },
        {
            name: 'Brigandine',
            size: 'M',
            dr: '3/d',
            def: -5,
            init: 5,
            rec: 3,
            fatigue: -1,
            skill: -4
        },
        {
            name: 'Laminar (Banded Mail)',
            size: 'M',
            dr: '3/d',
            def: 0,
            init: 5,
            rec: 4,
            fatigue: -3,
            skill: -4
        },
        {
            name: 'Chainmail',
            size: 'M',
            dr: '3/d',
            def: -3,
            init: 3,
            rec: 3,
            fatigue: -3,
            skill: -4
        },
        {
            name: 'Plated Mail',
            size: 'L',
            dr: '2/d + 6',
            def: -6,
            init: 6,
            rec: 6,
            fatigue: -6,
            skill: -6
        },
        {
            name: 'Scale',
            size: 'L',
            dr: '4/d + 2',
            def: -8,
            init: 7,
            rec: 5,
            fatigue: -5,
            skill: -8
        },
        {
            name: 'Full Plate',
            size: 'L',
            dr: '6/d + 7',
            def: -10,
            init: 10,
            rec: 9,
            fatigue: -8,
            skill: -8
        }
    ],
    shields: [
        {
            name: 'Buckler',
            dr: '6/d + 4',
            def: -1,
            parry: 5,
            cover: '1',
            flanks: 2,
            fatigue: -4,
            bonus: 'Yes',
            size: 'S'
        },
        {
            name: 'Clothe',
            dr: '6',
            def: 0,
            parry: 5,
            cover: '0',
            flanks: 2,
            fatigue: 0,
            bonus: false,
            size: 'S'
        },
        {
            name: 'Figure Eight',
            dr: '4/d + 4',
            def: -4,
            parry: 12,
            cover: 'd6!+4',
            flanks: 3,
            fatigue: -3,
            bonus: 'Yes',
            size: 'M'
        },
        {
            name: 'Heater',
            dr: '3/d + 6',
            def: -6,
            parry: 15,
            cover: 'd8!+4',
            flanks: 3,
            fatigue: -2,
            bonus: false,
            size: 'M'
        },
        {
            name: 'Hoplon',
            dr: '4/d + 4',
            def: -3,
            parry: 9,
            cover: 'd8!+7',
            flanks: 3,
            fatigue: -1,
            bonus: false,
            size: 'M'
        },
        {
            name: 'Kite',
            dr: '3/d + 2',
            def: -8,
            parry: 14,
            cover: '2d6!+8',
            flanks: 4,
            fatigue: -2,
            bonus: false,
            size: 'L'
        },
        {
            name: 'Pavise',
            dr: '4/d + 2',
            def: -8,
            parry: 0,
            cover: 'd20!+8',
            flanks: 1,
            fatigue: -5,
            bonus: 'Yes',
            size: 'L'
        },
        {
            name: 'Round',
            dr: '3/d + 2',
            def: -4,
            parry: 11,
            cover: 'd12!+6',
            flanks: 3,
            fatigue: -3,
            bonus: 'Yes',
            size: 'M'
        },
        {
            name: 'Tower',
            dr: '2/d + 1',
            def: -10,
            parry: 18,
            cover: '2d8!+10',
            flanks: 3,
            fatigue: -2,
            bonus: false,
            size: 'L'
        }
    ],
    weapons: {
        axes: [
            {
                name: 'Bardiche',
                size: 'L',
                dam: '5d4!',
                rec: 17,
                type: 'S',
                parry: 0,
                measure: 4,
                bonus: false,
            },
            {
                name: 'Battle Axe',
                size: 'M',
                dam: '3d6!',
                rec: 13,
                type: 'S',
                parry: 0,
                measure: 2.5,
                bonus: false,
            },
            {
                name: 'Handaxe',
                size: 'S',
                dam: '3d4!',
                rec: 11,
                type: 'S',
                parry: 0,
                measure: 1,
                bonus: 'Can be thrown.',
            },
            {
                name: 'Horsemans Pick',
                size: 'M',
                dam: 'd12!+d3!',
                rec: 9,
                type: 'P',
                parry: 0,
                measure: 2,
                bonus: false,
            },
            {
                name: 'Lochaber Axe',
                size: 'L',
                dam: '4d6!',
                rec: 19,
                type: 'S',
                parry: 0,
                measure: 6,
                bonus: false,
            }
        ],
        polearms: [
            {
                name: 'Ahlspiess',
                size: 'L',
                dam: '2d8!',
                rec: 8,
                type: 'P',
                parry: 0,
                measure: 6,
                bonus: 'Jab deals d6! damage.',
            },
            {
                name: 'Bill',
                size: 'L',
                dam: '4d4!',
                rec: 11,
                type: 'S',
                parry: 0,
                measure: 8,
                bonus: 'Dam x2 for Knock Backs vs mounted.',
            },
            {
                name: 'Glaive',
                size: 'L',
                dam: '8d3!',
                rec: 17,
                type: 'S',
                parry: 0,
                measure: 8,
                bonus: false,
            },
            {
                name: 'Guisarme',
                size: 'L',
                dam: '2d8!',
                rec: 8,
                type: 'P',
                parry: 0,
                measure: 7.5,
                bonus: 'Dam x2 for Knock Backs vs mounted.',
            },
            {
                name: 'Halberd',
                size: 'L',
                dam: '5d4!',
                rec: 15,
                type: 'S',
                parry: 0,
                measure: 5,
                bonus: 'Can be used as Piercing.',
            },
            {
                name: 'Halberd',
                size: 'L',
                dam: '2d8!',
                rec: 8,
                type: 'P',
                parry: 0,
                measure: 5,
                bonus: 'Can be used as Slashing.',
            },
            {
                name: 'Javelin',
                size: 'M',
                dam: '2d6!',
                rec: 9,
                type: 'P',
                parry: 0,
                measure: 4.25,
                bonus: 'Can be thrown.',
            },
            {
                name: 'Lance',
                size: 'L',
                dam: '1d8!',
                rec: 20,
                type: 'P',
                parry: 0,
                measure: 10,
                bonus: 'When mounted, +3d8! dam. Can be used 1 handed mounted.',
            },
            {
                name: 'Lucerne',
                size: 'L',
                dam: 'd20!',
                rec: 11,
                type: 'C',
                parry: 0,
                measure: 7,
                bonus: false,
            },
            {
                name: 'Military Fork',
                size: 'L',
                dam: '3d4!',
                rec: 9,
                type: 'P',
                parry: 0,
                measure: 6.75,
                bonus: 'Can be used to grab and thrown as 1 handed.',
            },
            {
                name: 'Pike',
                size: 'H',
                dam: '2d8!',
                rec: 8,
                type: 'P',
                parry: 0,
                measure: 13,
                bonus: false,
            },
            {
                name: 'Planson',
                size: 'S',
                dam: '2d6!',
                rec: 6,
                type: 'P',
                parry: 2,
                measure: 4,
                bonus: false,
            },
            {
                name: 'Ranseur',
                size: 'L',
                dam: '2d10!',
                rec: 10,
                type: 'P',
                parry: 0,
                measure: 7.25,
                bonus: false,
            },
            {
                name: 'Short Spear',
                size: 'M',
                dam: '2d8',
                rec: 7,
                type: 'P',
                parry: 0,
                measure: 5,
                bonus: false,
            },
            {
                name: 'Sovnya',
                size: 'L',
                dam: '6d3!',
                rec: 14,
                type: 'S',
                parry: 0,
                measure: 6.5,
                bonus: 'When mounted, +d8! damage.',
            },
            {
                name: 'Voulge',
                size: 'L',
                dam: '2d8!',
                rec: 6,
                type: 'P',
                parry: 0,
                measure: 8,
                bonus: false,
            },
            {
                name: 'War-scythe',
                size: 'L',
                dam: '6d3!',
                rec: 16,
                type: 'P',
                parry: 0,
                measure: 6.25,
                bonus: 'Also attacks 2 adjacent targets, dealing 3d3! damage on hit.',
            },
        ],
        sidearms: [
            {
                name: 'Brass Knuckles',
                size: 'S',
                dam: '1d8!',
                rec: 5,
                type: 'S',
                parry: 2,
                measure: 0,
                bonus: 'Can do all unarmed moves but Grab. Strikes +10.',
            },
            {
                name: 'Cinquedea',
                size: 'S',
                dam: '4d3!',
                rec: 12,
                type: 'S',
                parry: 0,
                measure: 1.5,
                bonus: false,
            },
            {
                name: 'Dagger',
                size: 'S',
                dam: '2d4!',
                rec: 5,
                type: 'P',
                parry: 2,
                measure: 1,
                bonus: 'Can be used as Piercing.',
            },
            {
                name: 'Dagger',
                size: 'S',
                dam: '3d3!',
                rec: 7,
                type: 'S',
                parry: 2,
                measure: 1,
                bonus: 'Can be used as Slashing.',
            },
            {
                name: 'Dusack',
                size: 'S',
                dam: '3d3!',
                rec: 7,
                type: 'S',
                parry: 2,
                measure: 2.5,
                bonus: 'Parry gives 3/D DR.',
            },
            {
                name: 'Katzbalger',
                size: 'S',
                dam: '1d3+2d4!',
                rec: 9,
                type: 'S',
                parry: 0,
                measure: .25,
                bonus: false,
            },
            {
                name: 'Knife',
                size: 'S',
                dam: '3d3!',
                rec: 7,
                type: 'S',
                parry: 0,
                measure: 0.75,
                bonus: 'Can be thrown.',
            },
            {
                name: 'Scourge',
                size: 'M',
                dam: '2d3!+d4!',
                rec: 8,
                type: 'S',
                parry: 0,
                measure: 2,
                bonus: 'Against Shields, +8 Atk; Against weapons w/ Parry, +4 Atk.',
            },
            {
                name: 'Stiletto',
                size: 'S',
                dam: 'd6!+d4!',
                rec: 4,
                type: 'P',
                parry: 4,
                measure: 1.5,
                bonus: false,
            },
        ],
        swords: [
            {
                name: 'Arming Sword',
                size: 'M',
                dam: '2d3!+1d4!',
                rec: 8,
                type: 'S',
                parry: 2,
                measure: 2.5,
                bonus: 'Add weapon\'s Parry to Shield\'s Parry.',
            },
            {
                name: 'Court Sword',
                size: 'S',
                dam: '2d6!',
                rec: 5,
                type: 'P',
                parry: 2,
                measure: 3.25,
                bonus: false,
            },
            {
                name: 'Estoc',
                size: 'M',
                dam: '2d6!',
                rec: 8,
                type: 'P',
                parry: 0,
                measure: 3.5,
                bonus: 'Half damage dice for /D DR.',
            },
            {
                name: 'Executioner\'s Sword',
                size: 'H',
                dam: '8d4!',
                rec: 24,
                type: 'S',
                parry: 0,
                measure: 10,
                bonus: false,
            },
            {
                name: 'Falchion',
                size: 'M',
                dam: '2d3!+2d4!',
                rec: 12,
                type: 'S',
                parry: 0,
                measure: 3,
                bonus: 'When used 2-handed, +6 damage instead.',
            },
            {
                name: 'Koncerz',
                size: 'M',
                dam: '2d6!',
                rec: 5,
                type: 'P',
                parry: 2,
                measure: 5.25,
                bonus: 'When mounted, +1d8! dam.',
            },
            {
                name: 'Longsword',
                size: 'M',
                dam: '3d3!+d4!',
                rec: 11,
                type: 'S',
                parry: 6,
                measure: 3.75,
                bonus: false,
            },
            {
                name: 'Messer',
                size: 'M',
                dam: '6d3!',
                rec: 15,
                type: 'S',
                parry: 3,
                measure: 2.5,
                bonus: false,
            },
            {
                name: 'Rapier',
                size: 'M',
                dam: '2d6!',
                rec: 5,
                type: 'P',
                parry: 4,
                measure: 4,
                bonus: false,
            },
            {
                name: 'Sabre',
                size: 'M',
                dam: '3d2!+2d3!',
                rec: 9,
                type: 'S',
                parry: 2,
                measure: 3,
                bonus: false,
            },
            {
                name: 'Schiavona',
                size: 'S',
                dam: '2d4!+d3!',
                rec: 6,
                type: 'S',
                parry: 2,
                measure: 2,
                bonus: false,
            },
            {
                name: 'Zweihander',
                size: 'L',
                dam: '7d3!',
                rec: 18,
                type: 'S',
                parry: 0,
                measure: 7,
                bonus: 'Also atks 2 adj. targets, dealing 3d3! damage on hit. +10 to Knock-Backs.',
            },
        ],
        trauma: [
            {
                name: 'Bec De Corbin',
                size: 'L',
                dam: '2d10!',
                rec: 14,
                type: 'C',
                parry: 0,
                measure: 6,
                bonus: false,
            },
            {
                name: 'Bludgeon',
                size: 'S',
                dam: '1d8!',
                rec: 7,
                type: 'C',
                parry: 0,
                measure: 2.25,
                bonus: 'Dam * 2 for Trauma.',
            },
            {
                name: 'Club',
                size: 'M',
                dam: 'd10!',
                rec: 6,
                type: 'C',
                parry: 0,
                measure: 1.5,
                bonus: false,
            },
            {
                name: 'Goedendag',
                size: 'L',
                dam: '2d8!',
                rec: 8,
                type: 'P',
                parry: 0,
                measure: 3.75,
                bonus: false,
            },
            {
                name: 'Great Hammer',
                size: 'H',
                dam: '2d12!+6',
                rec: 20,
                type: 'C',
                parry: 0,
                measure: 6,
                bonus: false,
            },
            {
                name: 'Mace',
                size: 'M',
                dam: '1d12!',
                rec: 8,
                type: 'C',
                parry: 0,
                measure: 2,
                bonus: false,
            },
            {
                name: 'Maul',
                size: 'L',
                dam: '2d12!',
                rec: 14,
                type: 'C',
                parry: 0,
                measure: 4,
                bonus: false,
            },
            {
                name: 'Peasant\'s Flail',
                size: 'L',
                dam: '1d20!',
                rec: 12,
                type: 'C',
                parry: 0,
                measure: 4,
                bonus: 'Against Shields, +8 Atk; Against weapons w/ Parry, +4 Atk.',
            },
            {
                name: 'Quarterstaff',
                size: 'L',
                dam: '1d10!',
                rec: 6,
                type: 'C',
                parry: 4,
                measure: 6,
                bonus: false,
            },
            {
                name: 'Unarmed',
                size: 'S',
                dam: '1d4!',
                rec: 5,
                type: 'C',
                parry: 0,
                measure: 0,
                bonus: 'Can performed unarmed moves.',
            },
            {
                name: 'War Flail',
                size: 'M',
                dam: '1d10!+1d4!',
                rec: 11,
                type: 'C',
                parry: 0,
                measure: 4,
                bonus: 'Against Shields, +8 Atk; Against weapons w/ Parry, +4 Atk.',
            },
            {
                name: 'War Hammer',
                size: 'M',
                dam: 'd12!+d4!',
                rec: 11,
                type: 'C',
                parry: 0,
                measure: .75,
                bonus: false,
            },
        ],
        thrown: [
            {
                name: 'Javelin',
                size: 'M',
                dam: '2d8!',
                rec: 10,
                type: 'P',
                minrec: 4,
                bonus: 'Can be used in melee. Apply Str Dam Mod.',
            },
            {
                name: 'Throwing Axe',
                size: 'S',
                dam: '4d3!!',
                rec: 9,
                type: 'S',
                minrec: 3,
                bonus: 'Can be used in melee. Apply Str Dam Mod.',
            },
            {
                name: 'Throwing Knife',
                size: 'S',
                dam: '2d6!',
                rec: 8,
                type: 'P',
                minrec: 3,
                bonus: 'Can be used in melee. Apply Str Dam Mod.',
            },
        ],
        mechanical: [
            {
                name: 'Bellybow',
                size: 'L',
                dam: '1d20!+1d6!',
                rec: 35,
                type: 'P',
                minrec: 5,
                bonus: 'Always 2-handed reload & used 2-handed. Steading weapon x2 Atk Skill Rank.',
            },
            {
                name: 'Composite Bow',
                size: 'M',
                dam: '1d12!+1d8!',
                rec: 12,
                type: 'P',
                minrec: 4,
                bonus: 'Can be used mounted. Always 2-handed reload & used 2-handed.',
            },
            {
                name: 'Crossbow',
                size: 'L',
                dam: '1d12!+1d4!',
                rec: 25,
                type: 'P',
                minrec: 5,
                bonus: 'Always 2-handed reload & used 2-handed. Steading weapon x2 Atk Skill Rank.',
            },
            {
                name: 'Latchet Crossbow',
                size: 'M',
                dam: '1d8!+1d4!',
                rec: 13,
                type: 'P',
                minrec: 4,
                bonus: 'Always 2-handed reload. Steading weapon x2 Atk Skill Rank.',
            },
            {
                name: 'Longbow',
                size: 'L',
                dam: 'd12+d10!',
                rec: 14,
                type: 'P',
                minrec: 5,
                bonus: 'Always 2-handed reload & used 2-handed.',
            },
            {
                name: 'Sling',
                size: 'S',
                dam: '1d10!',
                rec: 10,
                type: 'C',
                minrec: 3,
                bonus: false,
            },
            {
                name: 'Warbow',
                size: 'H',
                dam: '2d12!',
                rec: 14,
                type: 'P',
                minrec: 5,
                bonus: 'Must be fired from prone.',
            },
        ],
        firearms: [
            {
                name: 'Fire Lance',
                size: 'L',
                dam: '2d10!',
                rec: 14,
                type: 'C',
                minrec: 5,
                bonus: 'Causing Flinching. Gains 1 Wear on Atk.',
            },
            {
                name: 'Hakenbuchse',
                size: 'L',
                dam: '1d10!+1d8!',
                rec: 30,
                type: 'C',
                minrec: 5,
                bonus: 'Causing Flinching. Backfires.',
            },
            {
                name: 'Handgonne',
                size: 'M',
                dam: '1d10!+1d4!',
                rec: 18,
                type: 'C',
                minrec: 4,
                bonus: 'Causing Flinching. Backfires.',
            },
        ],
        ranges: [
            {
                name: 'Bellybow',
                range: 125
            },
            {
                name: 'Composite Bow',
                range: 50
            },
            {
                name: 'Crossbow',
                range: 100
            },
            {
                name: 'Fire Lance',
                range: 10
            },
            {
                name: 'Hakenbuchse',
                range: 50
            },
            {
                name: 'Handgonne',
                range: 30
            },
            {
                name: 'Javelin',
                range: 25
            },
            {
                name: 'Latchet Crossbow',
                range: 35
            },
            {
                name: 'Longbow',
                range: 250
            },
            {
                name: 'Throwing Axe',
                range: 10
            },
            {
                name: 'Throwing Knife',
                range: 15
            },
            {
                name: 'Sling',
                range: 30
            },
            {
                name: 'Warbow',
                range: 500
            },
        ]
    }
}

